### ISSUE TITLE
Contribution Queries

### ISSUE THREAD

**Issue by avinsrid** [CiscoDevNet/finesse-learning-labs#3]
Hi,

Currently, I found that there is no code sample that gives an overview of Finesse communication with REST API requests and XMPP BOSH. All the examples appear to be Javascript.

Can I provide sample code in C# to communicate with Finesse?

This might help others too!

~Avinash

**Comment by dekwan** [comment]
Hi Avinash,

Currently, we don't have a place for unofficial Finesse sample code. I think it is great that you want to share your sample code in C# because as you said, most of the sample code is in JavaScript.

I will have to work on figuring out what is the best mechanism to post unofficial sample code, but in the meantime, maybe you can post it to the DevNet Finesse forum: https://communities.cisco.com/community/developer/finesse

I am sure others would appreciate it.

Thanx,
Denise

**Comment by annegentle** [comment]
Hi, I know this is super old in tech years, but DevNet now has Code Exchange, where you can submit your own GitHub repos to be displayed on the DevNet site. See https://developer.cisco.com/codeexchange for details.
